### ISSUE TITLE
is there any way to supoort distributed database ?

### ISSUE THREAD

**Issue by showonlady** [s3team/Squirrel#43]
Our database TDSQL is an distributed database, it has multiple processes running for one database server, only a few processes provide client services, while others only provide computing services.  since the squrirrel now only collect the coverage info for one process, is there any way to support the multiple processes db testing?

**Comment by Changochen** [comment]
Thanks for your interests in using Squirrel. (FYI, @zr950624 and I are maintaining Squirrel now at [here](https://github.com/OMH4ck/Squirrel)). Squirrel doesn't care about how many processes are runing for the db server, as long as they are all instrumented for the code coverage. For the distributed setting, as long as you instrument the code so that it writes the coverage to a single bitmap, Squirrel should support it. However, that requires improving the instrumentation mechanism for AFL, which is out of the scope of Squirrel.
